### ISSUE TITLE
The actor died unexpectedly before finishing this task.

### ISSUE THREAD

**Issue by yichuan9527** [arcelien/pba#23]
Hi, I run "CUDA_VISIBLE_DEVICES=0 bash scripts/search.sh rsvhn", but reporting the error:      
`Traceback (most recent call last):
  File "/home/xiaopang/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 446, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/xiaopang/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 316, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/xiaopang/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 2197, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.`

**Comment by yichuan9527** [comment]
I dcline my TF's version from 1.14 to 1.10.
Now, it works.
Thanks!
