### ISSUE TITLE
TuneError when running PBA on Google Colab

### ISSUE THREAD

**Issue by MichaelMcAleer** [arcelien/pba#33]
Hi PBA Team,

I am trying to run PBA on Google Colab but im running into the below error when running any of the included scripts, any suggestions on what is going on here? I've searched for related errors but im not coming across anything apart from Ray github links to where the message is implemented in code.

```
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From pba/train.py:87: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From pba/train.py:87: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From pba/train.py:88: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From /content/drive/My Drive/Colab Notebooks/ResearchProject/pba/pba/setup.py:102: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

W0229 23:32:49.458530 140466326476672 module_wrapper.py:139] From /content/drive/My Drive/Colab Notebooks/ResearchProject/pba/pba/setup.py:102: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:Namespace(aug_policy='cifar10', bs=128, checkpoint_freq=0, cpu=4.0, data_path='/content/drive/My Drive/Colab Notebooks/ResearchProject/pba/datasets/', dataset='svhn', epochs=160, explore='cifar10', flatten=False, gpu=1.0, hp_policy='/content/drive/My Drive/Colab Notebooks/ResearchProject/pba/schedules/rsvhn_16_wrn.txt', hp_policy_epochs=160, local_dir='/content/drive/My Drive/Colab Notebooks/ResearchProject/pba/results/', lr=0.05, model_name='wrn_28_10', name='eval_svhn_wrn_28_10', no_aug=False, no_cutout=True, num_samples=1, proportion=1.0, recompute_dset_stats=False, restore=None, test_bs=25, train_size=1000, use_hp_policy=True, val_size=0, wd=0.01)
I0229 23:32:49.458748 140466326476672 setup.py:102] Namespace(aug_policy='cifar10', bs=128, checkpoint_freq=0, cpu=4.0, data_path='/content/drive/My Drive/Colab Notebooks/ResearchProject/pba/datasets/', dataset='svhn', epochs=160, explore='cifar10', flatten=False, gpu=1.0, hp_policy='/content/drive/My Drive/Colab Notebooks/ResearchProject/pba/schedules/rsvhn_16_wrn.txt', hp_policy_epochs=160, local_dir='/content/drive/My Drive/Colab Notebooks/ResearchProject/pba/results/', lr=0.05, model_name='wrn_28_10', name='eval_svhn_wrn_28_10', no_aug=False, no_cutout=True, num_samples=1, proportion=1.0, recompute_dset_stats=False, restore=None, test_bs=25, train_size=1000, use_hp_policy=True, val_size=0, wd=0.01)
INFO:tensorflow:data path: /content/drive/My Drive/Colab Notebooks/ResearchProject/pba/datasets/
I0229 23:32:49.458855 140466326476672 setup.py:119] data path: /content/drive/My Drive/Colab Notebooks/ResearchProject/pba/datasets/
INFO:tensorflow:overwriting with custom epochs
I0229 23:32:49.458990 140466326476672 setup.py:203] overwriting with custom epochs
INFO:tensorflow:epochs: 160, lr: 0.05, wd: 0.01
I0229 23:32:49.459068 140466326476672 setup.py:207] epochs: 160, lr: 0.05, wd: 0.01
2020-02-29 23:32:49,470	INFO resource_spec.py:212 -- Starting Ray with 6.54 GiB memory available for workers and up to 3.27 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-02-29 23:32:49,929	INFO services.py:1078 -- View the Ray dashboard at localhost:8265
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/experiment.py", line 185, in from_json
    exp = cls(name, run_value, **spec)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/experiment.py", line 110, in __init__
    self._run_identifier = Experiment.register_if_needed(run)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/experiment.py", line 218, in register_if_needed
    register_trainable(name, run_object)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/registry.py", line 67, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/registry.py", line 106, in register
    self._to_flush[(category, key)] = pickle.dumps(value)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _LazyLoader objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pba/train.py", line 88, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "pba/train.py", line 83, in main
    run_experiments({FLAGS.name: train_spec})
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/tune.py", line 396, in run_experiments
    experiments = convert_to_experiment_list(experiments)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/experiment.py", line 265, in convert_to_experiment_list
    for name, spec in experiments.items()
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/experiment.py", line 265, in <listcomp>
    for name, spec in experiments.items()
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/experiment.py", line 187, in from_json
    raise TuneError("Improper argument from JSON: {}.".format(spec))
ray.tune.error.TuneError: Improper argument from JSON: {'resources_per_trial': {'cpu': 4.0, 'gpu': 1.0}, 'stop': {'training_iteration': 160}, 'config': {'train_size': 1000, 'validation_size': 0, 'dataset': 'svhn', 'data_path': '/content/drive/My Drive/Colab Notebooks/ResearchProject/pba/datasets/', 'batch_size': 128, 'gradient_clipping_by_global_norm': 5.0, 'explore': 'cifar10', 'aug_policy': 'cifar10', 'no_cutout': True, 'recompute_dset_stats': False, 'lr': 0.05, 'weight_decay_rate': 0.01, 'test_batch_size': 25, 'proportion': 1.0, 'no_aug': False, 'use_hp_policy': True, 'hp_policy': '/content/drive/My Drive/Colab Notebooks/ResearchProject/pba/schedules/rsvhn_16_wrn.txt', 'hp_policy_epochs': 160, 'flatten': False, 'model_name': 'wrn', 'wrn_size': 160, 'wrn_depth': 28, 'num_epochs': 160}, 'local_dir': '/content/drive/My Drive/Colab Notebooks/ResearchProject/pba/results/', 'checkpoint_freq': 0, 'num_samples': 1}.
```

**Comment by arcelien** [comment]
Hi Michael, have you tried running on the command line instead of in colab? There may be a version dependency issue; see: https://github.com/arcelien/pba/blob/master/requirements.txt.

To understand more about the TuneError, you can also try opening an issue on the Ray github. I would suspect it may have to do with a newer version of Ray being backwards incompatible.

**Comment by MichaelMcAleer** [comment]
Im pretty limited when it comes to resources to run PBA so Colab is the only option at the moment. Spent the morning looking more into the version requirements and was able to get it running after some environment tinkering.  I had to remove Tensorflow and downgrade the Cuda libraries to 9.0 then install the few requirements that Colab needed after that.  I put together a script that I can run before executing the PBA scripts to setup Colab. If it helps anyone else ill add it here and close this one out. Thanks for pointing me in the right direction!

```
#!/bin/bash

TEXT_RESET='\e[0m'
TEXT_YELLOW='\e[1;33m'
start=$SECONDS

echo -e $TEXT_YELLOW'Current Cuda version...'$TEXT_RESET
nvcc --version

echo -e $TEXT_YELLOW'Uninstalling Cuda 10...'$TEXT_RESET
apt-get autoremove --purge cuda-1* -qq > /dev/null

echo -e $TEXT_YELLOW'Uninstalling Tensorflow...'$TEXT_RESET
pip uninstall -y -q tensorflow tensorflow-estimator tensorboard keras \
keras-applications keras-preprocessing

echo -e $TEXT_YELLOW'Downloading Cuda 9.0 installer...'$TEXT_RESET
wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb

echo -e $TEXT_YELLOW'Installing Cuda 9.0, this may take some time...'$TEXT_RESET
dpkg -i cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb
apt-key add /var/cuda-repo-9-0-local/7fa2af80.pub
apt-get update -qq > /dev/null
apt-get install cuda=9.0.176-1 -qq > /dev/null

echo -e $TEXT_YELLOW'Removing Cuda 9.0 installer files...'$TEXT_RESET
rm cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb*

echo -e $TEXT_YELLOW'Installing TensorFlow-GPU v1.11.0...'$TEXT_RESET
pip install -q tensorflow-gpu==1.11.0

echo -e $TEXT_YELLOW'Installing Ray v0.7.0...'$TEXT_RESET
pip install -q ray==0.7.0

echo -e $TEXT_YELLOW'Installing setproctitle...'$TEXT_RESET
pip install -q setproctitle

duration=$(( SECONDS - start ))

echo -e $TEXT_YELLOW'Installs complete, duration (s): ..'$duration $TEXT_RESET
nvcc --version
echo '---'
pip show tensorflow-gpu ray

echo -e $TEXT_YELLOW'Colab is now ready to run PBA...'$TEXT_RESET
```
