### ISSUE TITLE
RayOutOfMemoryError while doing PBA search.

### ISSUE THREAD

**Issue by amanrajdce** [arcelien/pba#36]
Hi, 
First of all thanks for a well-written code for this research work. I am using PBA search to find augmentation policy for depth estimation task. After training for some epochs Ray complains about **RayOutOfMemoryError** .
Package version:
```
ray==0.8.4
tensorflow-gpu=1.11.0
python==3.5.6
```
I initialize ray in the main script ``search.py`` with dedicated memory for workers.
```
  ray.init(
        webui_host='127.0.0.1',
        memory=1024 * 1024 * 1024 * 30,    # setting 30 GB for ray workers
        object_store_memory=1024 * 1024 * 1024 * 6  # setting 6 GB object store
    )
```
The reported error looks something like this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 381, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.6/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RayOutOfMemoryError): ^[[36mray::RayModel.train()^[[39m (pid=80, ip=10.244.16.90)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.6/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/ceph/amanraj/codes/pba-signet/pba/train.py", line 42, in _train
    eval_preds = self.trainer.run_model(self._iteration)
  File "/ceph/amanraj/codes/pba-signet/pba/model.py", line 165, in run_model
    self._run_training_loop(epoch)
  File "/ceph/amanraj/codes/pba-signet/pba/model.py", line 155, in _run_training_loop
    self.session, self.m, self.dataset, self.train_size, curr_epoch, self.comet_exp
  File "/ceph/amanraj/codes/pba-signet/pba/helper_utils.py", line 312, in run_epoch_training
    tgt_img, src_img_stack, tgt_img_aug, src_img_stack_aug, intrinsic = dataset.next_batch(batch_indxs, curr_epoch)
  File "/ceph/amanraj/codes/pba-signet/pba/data_utils.py", line 276, in next_batch
    ) for idx in indexes
ray.exceptions.RayTaskError(RayOutOfMemoryError): ^[[36mray::IDLE^[[39m (pid=83, ip=10.244.16.90)
File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task
  File "/usr/local/lib/python3.6/site-packages/ray/memory_monitor.py", line 120, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node amraj-pba-search5k-t4jfrl6-dm74m is used (45.88 / 48.0 GB). The top 10 memory consumers are:

PID     MEM     COMMAND
75      5.28GiB ray::RayModel.save_to_object()
81      3.96GiB ray::RayModel.train()
84      3.95GiB ray::RayModel.save()
80      3.94GiB ray::RayModel.train()
7       0.18GiB python pba/search.py --local_dir /ceph/amanraj/results/ --kitti_root /ceph/amanraj/data/kitti_proces
78      0.13GiB ray::pba.data_utils.augment_sample()
71      0.12GiB ray::IDLE
76      0.12GiB ray::IDLE
82      0.12GiB ray::IDLE
83      0.12GiB ray::IDLE

In addition, up to 18.59 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray.
```
My machine has a memory of **48GiB**, I don't understand how come Ray object store size is **18.59 GiB**  when I have already set in `ray.init()` it to be **6GiB**

Signature of relevant methods to give a gist of logic for reading and augmenting next batch of samples defined in `data_utils.py` ,  full code is omitted.

```
class TrainDataSet(object):
     def __init__(self, hparams):
          self.hparams = hparams
          ......
    def next_batch(self, indexes, iteration):
        batch_size = len(indexes)
        res = ray.get([
            augment_sample.remote(
                idx,
                iteration,
                self.data_loader,
                self.hparams.no_aug_policy,
                self.hparams.use_hp_policy,
                self.good_policies,
                self.policy,
                self.augmentation_transforms,
                self.input_height,
                self.input_width,
                self.hparams.flatten
            ) for idx in indexes
        ])
       for idx in range(0, batch_size):
          tgt_, src_img_stack_, tgt_aug_, src_img_stack_aug_, intrinsic_ = res[idx]
          # create batch from the returne output of each function call and return batch of samples.
           ...


        # batch_size = 8
        # tgt_img,  tgt_img_aug = (batch_size, 412, 126, 3)
        # src_img_stack,  src_img_stack_aug = (batch_size, 412, 126, 6)
        # intrinsic_batch = (batch_size, 3,3)
        return tgt_img_batch, src_img_stack_batch, tgt_img_aug_batch, src_img_stack_aug_batch, intrinsic_batch

@ray.remote
def augment_sample(
        sample_idx, iteration, data_loader, no_aug_policy, use_hp_policy,
        good_policies, policy, augmentation_transforms, input_height, input_width, flatten,
):
    """
    :param sample_idx: index of sample to be read
    :param iteration: current epoch of model
    :param data_loader: dataloader implementing __getitem__
    :param no_aug_policy: whether to use any policy or not
    :param use_hp_policy: whether to use hp policy or not
    :param good_policies: autoaugment policy
    :param policy: parsed policy
    :param augmentation_transforms: augmentation function
    :param input_height: height of input image
    :param input_width: width of input image
    :param flatten: randomly select an aug policy from schedule
    :return: return original and augmented sample
    """
    # read sample from disk
    tgt_img, src_img_1, src_img_2, intrinsic = data_loader[sample_idx]
    
    # apply augmentations and return original and augmented form of sample as numpy arrays
    ...

    return tgt_img, src_img_stack, tgt_img_aug, src_img_stack_aug, intrinsic

```

My remote function returns NumPy array, I suspect memory leak something related to Ray, but I am not able to figure out where this is happening. Any suggestions or input will be highly appreciated.  @ericl @neocxi 

PS: My previous data-loader was `torch.data.Dataset` based and It was working fine without any such crash but due to delay in augmentation, I adopted a purely ray-based code and parallelized it using` ray.remote` function calls.

**Comment by arcelien** [comment]
Hey, thanks for trying out the code!

Could this be an issue with dataloading? The dataloader implemented in this repo is fairly basic and loads all examples into memory.

For the issue with ray memory and object store, I'm not too familiar unfortunately, but you may have better luck asking in the ray github: https://github.com/ray-project/ray

**Comment by amanrajdce** [comment]
My dataloader is a ray remote function calls, all data lies on disk. Whenever I need a batch I run ray remote function in parallel `x` times, if my batchsize is` x.`

**Comment by arcelien** [comment]
I see - unfortunately, I'm not familiar with that use case. You'll be best be able to resolve it by asking in the Ray github.

**Comment by amanrajdce** [comment]
I was able to resolve this issue, by removing memory quota specifications in `ray.init()` . It turns out in container environment (kubernetes) setting the memory utilization quota makes the ray quickly utilization all of the memory. If I don't set it, it goes smoothly.

**Comment by amanrajdce** [comment]
I will close this for now and open it if I face this issue again. Thanks
